[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyevspace"
version = "0.14.2"
authors = [
    { name="Quinton Barnes", email="devqbizzle68@gmail.com" }
]
description = "A Python 3-dimensional Euclidean vector space."
readme = "README.md"
license = { file = "LICENCE.txt"}
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
"Homepage" = "https://github.com/qbizzle68/pyevspace"
"Bug Tracker" = "https://github.com/qbizzle68/pyevspace/issues"
