env_list = ["3.14", "3.13", "3.12", "3.11", "3.10"]

[env_run_base]
description = "run the test suite with pytest"
deps = [
    "pytest>=8",
    "setuptools>=68",
]
commands = [["pytest", {replace = "posargs", extend = true}]]

[env.lint]
description = "run linters on python {base_python}"
skip_install = true
deps = [
    "flake8",
    "flake8-pyproject",
]
commands = [["flake8", {replace = "posargs", extend = true}]]

[env.stubtest]
description = "runtime tests of stubs on python {base_python}"
deps = [
    "mypy",
]
commands = [["python", "-m", "mypy.stubtest", "pyevspace", {replace = "posargs", extend = true}]]