/* declarations of evector methods in the pyevspace c api */
#ifndef EVSPACE_VECTOR_DECL_H
#define EVSPACE_VECTOR_DECL_H

/* the macro definitions are found in evspace_vector_defn.h
	include that file before this one */

static EVSpace_Vector_add_RETURN EVSpace_Vector_add EVSpace_Vector_add_PROTO;
static EVSpace_Vector_sub_RETURN EVSpace_Vector_sub EVSpace_Vector_sub_PROTO;
static EVSpace_Vector_mult_RETURN EVSpace_Vector_mult EVSpace_Vector_mult_PROTO;
static EVSpace_Vector_neg_RETURN EVSpace_Vector_neg EVSpace_Vector_neg_PROTO;
static EVSpace_Vector_abs_RETURN EVSpace_Vector_abs EVSpace_Vector_abs_PROTO;
static EVSpace_Vector_iadd_RETURN EVSpace_Vector_iadd EVSpace_Vector_iadd_PROTO;
static EVSpace_Vector_isub_RETURN EVSpace_Vector_isub EVSpace_Vector_isub_PROTO;
static EVSpace_Vector_imult_RETURN EVSpace_Vector_imult EVSpace_Vector_imult_PROTO;
static EVSpace_Vector_div_RETURN EVSpace_Vector_div EVSpace_Vector_div_PROTO;
static EVSpace_Vector_idiv_RETURN EVSpace_Vector_idiv EVSpace_Vector_idiv_PROTO;
static EVSpace_Vector_eq_RETURN EVSpace_Vector_eq EVSpace_Vector_eq_PROTO;
static EVSpace_Vector_ne_RETURN EVSpace_Vector_ne EVSpace_Vector_ne_PROTO;
static EVSpace_Vector_dot_RETURN EVSpace_Vector_dot EVSpace_Vector_dot_PROTO;
static EVSpace_Vector_cross_RETURN EVSpace_Vector_cross EVSpace_Vector_cross_PROTO;
static EVSpace_Vector_mag_RETURN EVSpace_vector_mag EVSpace_Vector_mag_PROTO;
static EVSpace_Vector_mag2_RETURN EVSpace_Vector_mag2 EVSpace_Vector_mag2_PROTO;
static EVSpace_Vector_norm_RETURN EVSpace_Vector_norm EVSpace_Vector_norm_PROTO;
static EVSpace_Vector_inorm_RETURN EVSpace_Vector_inorm EVSpace_Vector_inorm_PROTO;
static EVSpace_Vector_vang_RETURN EVSpace_Vector_vang EVSpace_Vector_vang_PROTO;
static EVSpace_Vector_vxcl_RETURN EVSpace_Vector_vxcl EVSpace_Vector_vxcl_PROTO;

#endif // EVSPACE_VECTOR_DECL_H