/* declarations of ematrix metods in te pyevspace c api */
#ifndef EVSPACE_MATRIX_DECL_H
#define EVSPACE_MATRIX_DECL_H

/* te macro definitions are found in evspace_matrix_defn.h
	include that file before this one */

static EVSpace_Matrix_add_RETURN EVSpace_Matrix_add EVSpace_Matrix_add_PROTO;
static EVSpace_Matrix_sub_RETURN EVSpace_Matrix_sub EVSpace_Matrix_sub_PROTO;
static EVSpace_Matrix_multm_RETURN EVSpace_Matrix_multm EVSpace_Matrix_multm_PROTO;
static EVSpace_Matrix_multv_RETURN EVSpace_Matrix_multv EVSpace_Matrix_multv_PROTO;
static EVSpace_Matrix_multd_RETURN EVSpace_Matrix_multd EVSpace_Matrix_multd_PROTO;
static EVSpace_Matrix_neg_RETURN EVSpace_Matrix_neg EVSpace_Matrix_neg_PROTO;
static EVSpace_Matrix_iadd_RETURN EVSpace_Matrix_iadd EVSpace_Matrix_iadd_PROTO;
static EVSpace_Matrix_isub_RETURN EVSpace_Matrix_isub EVSpace_Matrix_isub_PROTO;
static EVSpace_Matrix_imultm_RETURN EVSpace_Matrix_imultm EVSpace_Matrix_imultm_PROTO;
static EVSpace_Matrix_imultd_RETURN EVSpace_Matrix_imultd EVSpace_Matrix_imultd_PROTO;
static EVSpace_Matrix_div_RETURN EVSpace_Matrix_div EVSpace_Matrix_div_PROTO;
static EVSpace_Matrix_idiv_RETURN EVSpace_Matrix_idiv EVSpace_Matrix_idiv_PROTO;
static EVSpace_Matrix_eq_RETURN EVSpace_Matrix_eq EVSpace_Matrix_eq_PROTO;
static EVSpace_Matrix_ne_RETURN EVSpace_Matrix_ne EVSpace_Matrix_ne_PROTO;
static EVSpace_Matrix_det_RETURN EVSpace_Matrix_det EVSpace_Matrix_det_PROTO;
static EVSpace_Matrix_trans_RETURN EVSpace_Matrix_trans EVSpace_Matrix_trans_PROTO;

#endif // EVSPACE_MATRIX_DECL_H