from typing import overload, Self
from collections.abc import Iterator, Iterable
from numbers import Real

class Vector:
    def __new__(self) -> Self: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[float]) -> None: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[float]: ...
    def __getitem__(self, _index: int) -> float: ...
    def __setitem__(self, _index: int, value: Real) -> None: ...
    def __buffer__(self, flags: int) -> memoryview: ...

    def __neg__(self) -> Self: ...
    def __add__(self, rhs: Self) -> Self: ...
    def __iadd__(self, rhs: Self) -> Self: ...
    def __sub__(self, rhs: Self) -> Self: ...
    def __isub__(self, rhs: Self) -> Self: ...
    def __mul__(self, rhs: Real) -> Self: ...
    def __imul__(self, rhs: Real) -> Self: ...
    def __rmul__(self, rhs: Real) -> Self: ...
    def __truediv__(self, rhs: Real) -> Self: ...
    def __itruediv__(self, rhs: Real) -> Self: ...
    def __matmul__(self, matrix: Matrix) -> Self: ...
    def __imatmul__(self, matrix: Matrix) -> Self: ...

    def __eq__(self, rhs: Self) -> bool: ...
    def __ne__(self, rhs: Self) -> bool: ...

    def __reduce__(self) -> tuple[Self, tuple[float, float, float]]: ...

    def magnitude(self) -> float: ...
    def magnitued_squared(self) -> float: ...
    def normalize(self) -> None: ...
    def norm(self) -> Self: ...


class Matrix:
    
    def __new__() -> Self: ...
    @overload
    def __init__() -> None: ...
    @overload
    def __init__(row1: Iterable[Real, 3]) -> None: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    @overload
    def __getitem__(self, row_index: int) -> memoryview: ...
    @overload
    def __getitem__(self, row_index: int, col_index: int) -> float: ...
    @overload
    def __getitem__(self, row_index: int, col_index: slice) -> memoryview: ...
    @overload
    def __getitem__(self, row_index: slice, col_index: int) -> memoryview: ...
    @overload
    def __getitem__(self, row_index: slice, col_index: slice) -> memoryview: ...
    def __buffer__(self, flags: int) -> memoryview: ...

    def __neg__(self) -> Self: ...
    def __add__(self, rhs: Self) -> Self: ...
    def __iadd__(self, rhs: Self) -> Self: ...
    def __sub__(self, rhs: Self) -> Self: ...
    def __isub__(self, rhs: Self) -> Self: ...
    def __mul__(self, rhs: Real) -> Self: ...
    def __imul__(self, rhs: Real) -> Self: ...
    def __rmul__(self, rhs: Real) -> Self: ...
    def __truediv__(self, rhs: Real) -> Self: ...
    def __itruediv__(self, rhs: Real) -> Self: ...
    @overload
    def __matmul__(self, rhs: Vector) -> Vector: ...
    @overload
    def __matmul__(self, rhs: Self) -> Self: ...
    def __imatmul__(self, rhs: Self) -> Self: ...

    def __eq__(self, rhs: Self) -> bool: ...
    def __ne__(self, rhs: Self) -> bool: ...

    def __reduce__(self) -> tuple[Matrix, tuple[tuple[float, ...], ...]]: ...
    
    def transpose(self) -> None: ...
    def transpose_inplace(self) -> Self: ...
    def determinate(self) -> float: ...
    def inverse(self) -> Self: ...
