from typing import overload, Self
from collections.abc import Iterator, Iterable
from numbers import Real

class Vector:
    def __new__(self) -> Self: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: Real, y: Real, z: Real) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[Real]) -> None: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[float]: ...
    def __getitem__(self, _index: int) -> float: ...
    def __setitem__(self, _index: int, value: Real) -> None: ...
    def __buffer__(self, flags: int) -> memoryview: ...

    def __neg__(self) -> Self: ...
    def __add__(self, rhs: Self) -> Self: ...
    def __iadd__(self, rhs: Self) -> Self: ...
    def __sub__(self, rhs: Self) -> Self: ...
    def __isub__(self, rhs: Self) -> Self: ...
    def __mul__(self, rhs: Real) -> Self: ...
    def __imul__(self, rhs: Real) -> Self: ...
    def __rmul__(self, rhs: Real) -> Self: ...
    def __truediv__(self, rhs: Real) -> Self: ...
    def __itruediv__(self, rhs: Real) -> Self: ...
    def __matmul__(self, matrix: Matrix) -> Self: ...
    def __imatmul__(self, matrix: Matrix) -> Self: ...

    def __eq__(self, rhs: Self) -> bool: ...
    def __ne__(self, rhs: Self) -> bool: ...

    def __reduce__(self) -> tuple[Self, tuple[float, float, float]]: ...

    def magnitude(self) -> float: ...
    def magnitued_squared(self) -> float: ...
    def normalize(self) -> None: ...
    def norm(self) -> Self: ...
    def compare_to_ulp(self, rhs: Self, max_ulps: int) -> bool: ...
    def compare_to_tol(self, rel_tol: float = 1e-9, abs_tol: float = 1e-15) -> bool: ...

    @property
    def E1(self) -> Self: ...
    @property
    def E2(self) -> Self: ...
    @property
    def E3(self) -> Self: ...


class Matrix:
    
    def __new__() -> Self: ...
    @overload
    def __init__() -> None: ...
    @overload
    def __init__(row1: Iterable[Real, 3]) -> None: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    @overload
    def __getitem__(self, row_index: int) -> memoryview: ...
    @overload
    def __getitem__(self, row_index: int, col_index: int) -> float: ...
    @overload
    def __getitem__(self, row_index: int, col_index: slice) -> memoryview: ...
    @overload
    def __getitem__(self, row_index: slice, col_index: int) -> memoryview: ...
    @overload
    def __getitem__(self, row_index: slice, col_index: slice) -> memoryview: ...
    def __buffer__(self, flags: int) -> memoryview: ...

    def __neg__(self) -> Self: ...
    def __add__(self, rhs: Self) -> Self: ...
    def __iadd__(self, rhs: Self) -> Self: ...
    def __sub__(self, rhs: Self) -> Self: ...
    def __isub__(self, rhs: Self) -> Self: ...
    def __mul__(self, rhs: Real) -> Self: ...
    def __imul__(self, rhs: Real) -> Self: ...
    def __rmul__(self, rhs: Real) -> Self: ...
    def __truediv__(self, rhs: Real) -> Self: ...
    def __itruediv__(self, rhs: Real) -> Self: ...
    @overload
    def __matmul__(self, rhs: Vector) -> Vector: ...
    @overload
    def __matmul__(self, rhs: Self) -> Self: ...
    def __imatmul__(self, rhs: Self) -> Self: ...

    def __eq__(self, rhs: Self) -> bool: ...
    def __ne__(self, rhs: Self) -> bool: ...

    def __reduce__(self) -> tuple[Matrix, tuple[tuple[float, ...], ...]]: ...
    
    def transpose(self) -> None: ...
    def transpose_inplace(self) -> Self: ...
    def determinate(self) -> float: ...
    def inverse(self) -> Self: ...
    def compare_to_ulp(self, rhs: Self, max_ulps: int) -> bool: ...
    def compare_to_tol(self, rhs: Self, rel_tol: float = 1e-9, abs_tol: float = 1e-15) -> bool: ...

    @property
    def IDENTITY(self) -> Self: ...

class EulerAngles:
    
    def __new__(cls) -> Self: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, alpha: Real, beta: Real, gamma: Real) -> None: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    def __getitem__(self, index_: int) -> float: ...
    def __setitem__(self, index_: int, value: Real) -> None: ...

    def __reduce__(cls) -> tuple: ...


class RotationOrder:

    def __getitem__(self, index_: int) -> float: ...
    
    def __reduce__(cls) -> tuple: ...

    def __eq__(self, other: RotationOrder) -> bool: ...
    def __ne__(self, other: RotationOrder) -> bool: ...
    def __hash__(self) -> int: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    @property
    def first(self) -> float: ...

    @property
    def second(self) -> float: ...

    @property
    def third(self) -> float: ...


X_AXIS: int = 0
Y_AXIS: int = 1
Z_AXIS: int = 2

XYZ: RotationOrder = RotationOrder(X_AXIS, Y_AXIS, Z_AXIS)
XZY: RotationOrder = RotationOrder(X_AXIS, Z_AXIS, Y_AXIS)
YXZ: RotationOrder = RotationOrder(Y_AXIS, X_AXIS, Z_AXIS)
YZX: RotationOrder = RotationOrder(Y_AXIS, Z_AXIS, X_AXIS)
ZXY: RotationOrder = RotationOrder(Z_AXIS, X_AXIS, Y_AXIS)
ZYX: RotationOrder = RotationOrder(Z_AXIS, Y_AXIS, X_AXIS)
XYX: RotationOrder = RotationOrder(X_AXIS, Y_AXIS, X_AXIS)
XZX: RotationOrder = RotationOrder(X_AXIS, Z_AXIS, X_AXIS)
YXY: RotationOrder = RotationOrder(Y_AXIS, X_AXIS, Y_AXIS)
YZY: RotationOrder = RotationOrder(Y_AXIS, Z_AXIS, Y_AXIS)
ZXZ: RotationOrder = RotationOrder(Z_AXIS, X_AXIS, Z_AXIS)
ZYZ: RotationOrder = RotationOrder(Z_AXIS, Y_AXIS, Z_AXIS)


class ReferenceFrame:
    def __new__(cls, order: RotationOrder, angles: EulerAngles, *,
                offset: Vector = None, intrinsic: bool = True) -> Self: ...
    
    def get_matrix(self) -> Matrix: ...
    def get_angles(self) -> EulerAngles: ...

    @overload
    def set_angles(alpha: Real | None = None, beta: Real | None = None,
                   gamma: Real | None = None) -> None: ...
    @overload
    def set_angles(angles: EulerAngles) -> None: ...

    @overload
    def rotate_to(vector: Vector) -> Vector: ...
    @overload
    def rotate_to(frame: Self, vector: Vector) -> Vector: ...

    @overload
    def rotate_from(vector: Vector) -> Vector: ...
    @overload
    def rotate_from(frame: Self, vector: Vector) -> Vector: ...

    @property
    def offset(self) -> Vector: ...

    @offset.setter
    def offset(self, value: Vector) -> Vector: ...

    @property
    def intrinsic(self) -> bool: ...


def vector_dot(lhs: Vector, rhs: Vector) -> float: ...
def vector_cross(lhs: Vector, rhs: Vector) -> Vector: ...
def vector_angle(from_: Vector, to: Vector) -> Vector: ...
def vector_exclude(vector: Vector, exclude: Vector) -> Vector: ...
def vecor_proj(project: Vector, onto: Vector) -> Vector: ...

@overload
def rotate_from(matrix: Matrix, vector: Vector, *, offset: Vector = None) \
    -> Vector: ...
@overload
def rotate_from(angle: Real, axis: int | Vector, vector: Vector, *,
                offset: Vector = None) -> Vector: ...
@overload
def rotate_from(order: RotationOrder, angles: EulerAngles, vector: Vector, *,
                offset: Vector = None, intrinsic: bool = True) -> Vector: ...

@overload
def rotate_to(matrix: Matrix, vector: Vector, *, offset: Vector = None) \
    -> Vector: ...
@overload
def rotate_to(angle: Real, axis: int | Vector, vector: Vector, *,
                offset: Vector = None) -> Vector: ...
@overload
def rotate_to(order: RotationOrder, angles: EulerAngles, vector: Vector, *,
                offset: Vector = None, intrinsic: bool = True) -> Vector: ...

def rotate_between(order_from: RotationOrder, angles_from: EulerAngles,
                   order_to: RotationOrder, angles_to: EulerAngles, *,
                   intrinsic_from: bool = True, intrinsic_to: bool = True,
                   offset_from: Vector = None, offset_to: Vector = None) \
                   -> Vector: ...
