from typing import overload, Self
from collections.abc import Iterator, Iterable
from numbers import Real

class Vector:
    def __new__(self) -> Self: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[float]) -> None: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[float]: ...
    def __getitem__(self, _index: int) -> float: ...
    def __setitem__(self, _index: int, value: Real) -> None: ...
    def __buffer__(self, flags: int) -> memoryview: ...

    def __neg__(self) -> Self: ...
    def __add__(self, rhs: Self) -> Self: ...
    def __iadd__(self, rhs: Self) -> Self: ...
    def __sub__(self, rhs: Self) -> Self: ...
    def __isub__(self, rhs: Self) -> Self: ...
    def __mul__(self, rhs: Real) -> Self: ...
    def __imul__(self, rhs: Real) -> Self: ...
    def __rmul__(self, rhs: Real) -> Self: ...
    def __truediv__(self, rhs: Real) -> Self: ...
    def __itruediv__(self, rhs: Real) -> Self: ...
    def __matmul__(self, matrix: Matrix) -> Self: ...
    def __imatmul__(self, matrix: Matrix) -> Self: ...

    def __eq__(self, rhs: Self) -> bool: ...
    def __ne__(self, rhs: Self) -> bool: ...

    def __reduce__(self) -> tuple[Self, tuple[float, float, float]]: ...

    def magnitude(self) -> float: ...
    def magnitued_squared(self) -> float: ...
    def normalize(self) -> None: ...
    def norm(self) -> Self: ...
    def compare_to_ulp(self, rhs: Self, max_ulps: int) -> bool: ...
    def compare_to_tol(self, rel_tol: float = 1e-9, abs_tol: float = 1e-15) -> bool: ...


class Matrix:
    
    def __new__() -> Self: ...
    @overload
    def __init__() -> None: ...
    @overload
    def __init__(row1: Iterable[Real, 3]) -> None: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    @overload
    def __getitem__(self, row_index: int) -> memoryview: ...
    @overload
    def __getitem__(self, row_index: int, col_index: int) -> float: ...
    @overload
    def __getitem__(self, row_index: int, col_index: slice) -> memoryview: ...
    @overload
    def __getitem__(self, row_index: slice, col_index: int) -> memoryview: ...
    @overload
    def __getitem__(self, row_index: slice, col_index: slice) -> memoryview: ...
    def __buffer__(self, flags: int) -> memoryview: ...

    def __neg__(self) -> Self: ...
    def __add__(self, rhs: Self) -> Self: ...
    def __iadd__(self, rhs: Self) -> Self: ...
    def __sub__(self, rhs: Self) -> Self: ...
    def __isub__(self, rhs: Self) -> Self: ...
    def __mul__(self, rhs: Real) -> Self: ...
    def __imul__(self, rhs: Real) -> Self: ...
    def __rmul__(self, rhs: Real) -> Self: ...
    def __truediv__(self, rhs: Real) -> Self: ...
    def __itruediv__(self, rhs: Real) -> Self: ...
    @overload
    def __matmul__(self, rhs: Vector) -> Vector: ...
    @overload
    def __matmul__(self, rhs: Self) -> Self: ...
    def __imatmul__(self, rhs: Self) -> Self: ...

    def __eq__(self, rhs: Self) -> bool: ...
    def __ne__(self, rhs: Self) -> bool: ...

    def __reduce__(self) -> tuple[Matrix, tuple[tuple[float, ...], ...]]: ...
    
    def transpose(self) -> None: ...
    def transpose_inplace(self) -> Self: ...
    def determinate(self) -> float: ...
    def inverse(self) -> Self: ...
    def compare_to_ulp(self, rhs: Self, max_ulps: int) -> bool: ...
    def compare_to_tol(self, rhs: Self, rel_tol: float = 1e-9, abs_tol: float = 1e-15) -> bool: ...

class EulerAngles:
    
    def __new__(cls) -> Self: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, alpha: float, beta: float, gamma: float) -> None: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    def __getitem__(self, index_: int) -> float: ...
    def __setitem__(self, index_: int, value: Real) -> None: ...

    def __reduce__(cls) -> tuple: ...

    @property
    def alpha(self) -> float: ...

    @property
    def beta(self) -> float: ...

    @property
    def gamma(self) -> float: ...


class RotationOrder:

    def __getitem__(self, index_: int) -> float: ...
    
    def __reduce__(cls) -> tuple: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    @property
    def first(self) -> float: ...

    @property
    def second(self) -> float: ...

    @property
    def third(self) -> float: ...


# X_AXIS: int = 0
# Y_AXIS: int = 1
# Z_AXIS: int = 2

# XYZ: RotationOrder
# XZY: RotationOrder
# YXZ: RotationOrder
# YZX: RotationOrder
# ZXY: RotationOrder
# ZYX: RotationOrder
# XYX: RotationOrder
# XZX: RotationOrder
# YXY: RotationOrder
# YZY: RotationOrder
# ZXZ: RotationOrder
# ZYZ: RotationOrder


def vector_dot(lhs: Vector, rhs: Vector) -> float: ...
def vector_cross(lhs: Vector, rhs: Vector) -> Vector: ...
def vector_angle(from_: Vector, to: Vector) -> Vector: ...
def vector_exclude(vector: Vector, exclude: Vector) -> Vector: ...
def vecor_proj(project: Vector, onto: Vector) -> Vector: ...

@overload
def rotate_from(matrix: Matrix, vector: Vector, *, offset: Vector = None) \
    -> Vector: ...
@overload
def rotate_from(angle: float, axis: int | Vector, vector: Vector, *,
                offset: Vector = None) -> Vector: ...
@overload
def rotate_from(order: RotationOrder, angles: EulerAngles, vector: Vector, *,
                offset: Vector = None, intrinsic: bool = True) -> Vector: ...

@overload
def rotate_to(matrix: Matrix, vector: Vector, *, offset: Vector = None) \
    -> Vector: ...
@overload
def rotate_to(angle: float, axis: int | Vector, vector: Vector, *,
                offset: Vector = None) -> Vector: ...
@overload
def rotate_to(order: RotationOrder, angles: EulerAngles, vector: Vector, *,
                offset: Vector = None, intrinsic: bool = True) -> Vector: ...

def rotate_between(order_from: RotationOrder, angles_from: EulerAngles,
                   order_to: RotationOrder, angles_to: EulerAngles,
                   intrinsic_from: bool = True, intrinsic_to: bool = True,
                   offset_from: Vector = None, offset_to: Vector = None) \
                   -> Vector: ...
