from importlib.metadata import version, PackageNotFoundError

from ._pyevspace import (
    Vector,
    vector_dot,
    vector_cross,
    vector_angle,
    vector_exclude,
    vector_proj,
    Matrix,
    EulerAngles,
    RotationOrder,
    compute_rotation_matrix,
    rotate_from,
    rotate_to,
    rotate_between,
    ReferenceFrame,
    X_AXIS,
    Y_AXIS,
    Z_AXIS,
    XYZ,
    XZY,
    YXZ,
    YZX,
    ZXY,
    ZYX,
    XYX,
    XZX,
    YXY,
    YZY,
    ZXZ,
    ZYZ,
)

__all__ = (
    'Vector',
    'vector_dot',
    'vector_cross',
    'vector_angle',
    'vector_exclude',
    'vector_proj',
    'Matrix',
    'EulerAngles',
    'RotationOrder',
    'compute_rotation_matrix',
    'rotate_from',
    'rotate_to',
    'rotate_between',
    'ReferenceFrame',
    'X_AXIS',
    'Y_AXIS',
    'Z_AXIS',
    'XYZ',
    'XZY',
    'YXZ',
    'YZX',
    'ZXY',
    'ZYX',
    'XYX',
    'XZX',
    'YXY',
    'YZY',
    'ZXZ',
    'ZYZ',
)

try:
    __version__ = version("pyevspace")
except PackageNotFoundError:
    __version__ = "unknown"
