from pyevspace import (
    Vector, Matrix, EulerAngles, RotationOrder, ReferenceFrame
)

def vector_capsule_c(vector: Vector) -> tuple[Vector]: ...
def matrix_capsule_c(matrix: Matrix) -> tuple[Matrix]: ...
def angles_capsule_c(angles: EulerAngles) -> tuple[EulerAngles]: ...
def order_capsule_c(order: RotationOrder) -> tuple[RotationOrder]: ...
def frame_capsule_c(frame: ReferenceFrame, frame_offset: ReferenceFrame)\
    -> tuple[ReferenceFrame]: ...
