from pyevspace import (
    Vector, Matrix, EulerAngles, RotationOrder, ReferenceFrame
)

def vector_capsule_cpp(vector: Vector) -> tuple[Vector]: ...
def matrix_capsule_cpp(matrix: Matrix) -> tuple[Matrix]: ...
def angles_capsule_cpp(angles: EulerAngles) -> tuple[EulerAngles]: ...
def order_capsule_cpp(order: RotationOrder) -> tuple[RotationOrder]: ...
def frame_capsule_cpp(frame: ReferenceFrame, frame_offset: ReferenceFrame)\
    -> tuple[ReferenceFrame]: ...