#!/usr/bin/env bash

# Executes builds to ensure behavior before a push to remote. Documentation
# is built in a temporary directory and important targets are ran using Tox.

for arg in "$@"; do
    if [[ "$arg" == "--help" ]] || [[ "$arg" == "-h" ]]; then
        echo -e "Syntax: $0 [--help|-h]\n\n\
Tests all builds across the project which includes documentation build (into)\n\
a temp directory, tox buiilds and tests in all supported versions, and linting\n\
and stubtests.\n"
    exit 0
    fi
done

RED="\E[0;31m"
GREEN="\E[0;32m"
YELLOW="\E[0;33m"
CLEAR="\E[0m"

print_color() {
    COLOR="$1"
    MSG="$2"

    echo -e "${COLOR}${MSG}${CLEAR}"
}

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

print_color $YELLOW "Building sphinx documentation"
sphinx-build -b html docs/source "$TMP_DIR"
if [[ "$?" -eq "0" ]]; then
    print_color $GREEN "Documentation build successful"
else
    print_color $RED "Documentation build failed"
fi

echo -e "${YELLOW}Running Tox environments${CLEAR}"
tox -e "3.10","3.11","3.12","3.13","3.14","lint","stubtest"
