# This workflow will generate a new release when a new tag of the form
# v#.#.# is pushed to the repository.

name: Create new release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]'
  
jobs:
  verify-versions:
    name: Validate all version numbers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Validate versions
        run: .github/scripts/verify_versions.py ${{ github.ref_name }}

  release:
    name: Create Release
    needs: verify-versions
    permissions: write-all

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Get changes from change log
        run: python .github/scripts/generate_changes.py ${{ github.ref_name }} ${{ github.workspace }}/CHANGELOG.md tmp.md
        
      - name: Create formatted change log file for create-release
        run: |
          echo -n "## PyEVSpace Version " >> changes.md
          echo ${{ github.ref_name }} | cut -d'v' -f 2 >> changes.md
          printf "\n" >> changes.md
          cat tmp.md >> changes.md
        
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body_path: changes.md
  