# This workflow builds all wheels and the sdist for pyevspace, then
# published the version to the PyPi repository.
# This workflow also builds the documentation using Sphinx, then uploads
# it to the documentation's hosted server.

name: Publish python package and documentation

on: 
  release:
    type: [published]

env:
  SPHINX_BUILD_PATH: docs/build

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.14.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # pyevspace source does not support 3.6 or 3.7 CPython
          CIBW_SKIP: cp36-* cp37-*
          CIBW_BUILD_FRONTEND: "build"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    name: Upload wheels to PyPi test repository.
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pyevspace
    permissions:
      id-token: write
    steps:
      - name: Retrieve build artifacts.
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  build_docs:
    name: Build documentation using Sphinx
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - uses: actions/setup-python@v3
  
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx pydata-sphinx-theme

      - name: Build documentation
        run: |
          sphinx-build -b html docs/source ${{ env.SPHINX_BUILD_PATH }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: |
            ${{ env.SPHINX_BUILD_PATH }}/*.html
            ${{ env.SPHINX_BUILD_PATH }}/*.js
            ${{ env.SPHINX_BUILD_PATH }}/*/
            !${{ env.SPHINX_BUILD_PATH }}/_sources
            !${{ env.SPHINX_BUILD_PATH }}/.doctrees

  deploy_docs:
    name: Deploy documentation to server
    needs: [build_docs, upload_pypi]
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: documentation

      - name: Upload files using SFTP
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrest.DH_HOST }}
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_PASS }}
          localDir: '.'
          remoteDir: 'qbizzle.com/pyevspace'
