# This workflow builds all wheels and the sdist for pyevspace, then
# published the version to the PyPi repository.

name: Upload python package

on: 
  release:
    type: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.14.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # pyevspace source does not support 3.6 or 3.7 CPython
          CIBW_SKIP: cp36-* cp37-*
          CIBW_BUILD_FRONTEND: "build"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    name: Upload wheels to PyPi test repository.
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/pyevspace
    permissions:
      id-token: write
    steps:
      - name: Retrieve build artifacts.
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
