# This workflow will build the package and run all tests on all supported python
# versions (3.8 - 3.11) and on all three major operating systems.

name: Tests

on:
  push:
    paths:
      - 'setup.py'
      - 'pyproject.toml'
      - 'MANIFEST.in'
      - 'src/pyevspace/**'
      - 'src/tests/**'

permissions:
  contents: read

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
      
    steps:
    - uses: actions/checkout@v3
  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Build and install extension
      run: pip install .

    - name: Test with unittest
      run: python -m unittest src.tests
