#!/usr/bin/env bash

while read local_ref local_sha remote_ref remote_sha; do
    if [[ "$local_ref" == refs/tags/* ]]; then
        tag_name="${local_ref#refs/tags/}"
        version="${tag_name#v}"

        if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ERROR: Version tag contains pre-release info ($version)" 2>&1
            exit 1
        fi

        echo "Verifying all repo versions match $version"

        toml_version=$(grep '^version' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
        if [[ "$toml_version" != "$version" ]]; then
            echo "ERROR: pyproject.toml version ($toml_version) does not match tag ($version)" 1>&2
            exit 1
        fi

        readme_version=$(grep '# PyEVSpace' README.md | sed 's/# PyEVSpace \(.*\)/\1/')
        if [[ "$readme_version" != "$version" ]]; then
            echo "ERROR: README.md version($readme_version) does not match tag ($version)" 1>&2
            exit 1
        fi

        cat CHANGELOG.md | grep -q "##\s*\[${first_value}\]" > /dev/null
        if [[ "$?" -ne "0" ]]; then
            echo "ERROR: Version ($version) doesn't appear in CHANGELOG.md" 1>&2
            exit 1
        fi

        echo All versions match
        exit 0
    fi
done